import { Outfit } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// ThemeProvider
import { ThemeProvider } from "@/components/ThemeProvider";

// Redux
import { ReduxProvider } from "@/redux/provider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "profile website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body className={outfit.className}>
        <ReduxProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
